# Gemini On-Demand Assistant Template
# Copy to: .github/workflows/gemini-on-demand.yml
#
# Usage: Comment on any issue or PR with @gemini-cli followed by your question.
# For code review: @gemini-cli /code-review
#
# PREREQUISITES:
#   1. Add GEMINI_API_KEY to GitHub repo secrets
#   2. Optionally set GEMINI_MODEL as a repo variable

name: Gemini On-Demand Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  MAX_DIFF_BYTES: 51200  # 50KB max diff size

jobs:
  gemini-assist:
    if: contains(github.event.comment.body, '@gemini-cli')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install @google/generative-ai

      - name: Process request
        id: process
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: ${{ vars.GEMINI_MODEL }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          cat > on-demand.js << 'SCRIPT'
          const { GoogleGenerativeAI } = require('@google/generative-ai');
          const fs = require('fs');
          const { execSync } = require('child_process');

          async function main() {
            const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
            const modelName = process.env.GEMINI_MODEL || 'gemini-2.5-pro';
            const model = genAI.getGenerativeModel({ model: modelName });
            const defaultBranch = process.env.DEFAULT_BRANCH || 'master';
            const maxDiffBytes = parseInt(process.env.MAX_DIFF_BYTES) || 51200;

            console.log('Using Gemini model: ' + modelName);

            // Load project context
            let context = '';
            try {
              context = fs.readFileSync('GEMINI.md', 'utf8');
            } catch (e) {
              console.log('Warning: GEMINI.md not found');
            }

            const userQuestion = process.env.COMMENT_BODY.replace(/@gemini-cli\s*/gi, '').trim();
            const isCodeReview = userQuestion.toLowerCase().includes('/code-review');

            let prompt = '';

            if (isCodeReview) {
              // Get diff with error handling (may fail on issues or if no diff exists)
              let diff = '';
              try {
                diff = execSync(
                  'git diff origin/' + defaultBranch + '...HEAD' +
                  ' -- . ":!*.lock" ":!*.png" ":!*.jpg" ":!coverage/" ":!.next/" ":!dist/" ":!*.min.js" ":!package-lock.json"',
                  { encoding: 'utf8', maxBuffer: 10 * 1024 * 1024 }
                );
              } catch (err) {
                console.log('Warning: Could not generate diff — this may be an issue (not a PR), or the branch has no changes.');
                diff = '(No diff available — this comment may be on an issue rather than a PR)';
              }

              // Truncate large diffs
              if (Buffer.byteLength(diff) > maxDiffBytes) {
                const originalSize = Buffer.byteLength(diff);
                diff = diff.substring(0, maxDiffBytes);
                diff += '\n\n... [TRUNCATED — diff was ' + originalSize + ' bytes, showing first ' + maxDiffBytes + ']';
              }

              prompt = 'You are reviewing code for this project.\n\n' +
                'PROJECT CONTEXT:\n' + context + '\n\n' +
                'USER REQUEST: ' + userQuestion + '\n\n' +
                'CODE CHANGES:\n```diff\n' + diff + '\n```\n\n' +
                'Provide a thorough code review focusing on architecture, security, and quality.\n' +
                'Format with sections: Critical Issues, High Priority, Medium Priority, Low Priority.';
            } else {
              prompt = 'You are a helpful assistant for this project.\n\n' +
                'PROJECT CONTEXT:\n' + context + '\n\n' +
                'USER QUESTION: ' + userQuestion + '\n\n' +
                'Provide a helpful, specific answer. Be concise but thorough.';
            }

            try {
              const result = await model.generateContent(prompt);
              const response = await result.response;
              fs.writeFileSync('response.md', response.text());
              console.log(response.text());
            } catch (error) {
              console.error('Error calling Gemini API:', error.message);
              fs.writeFileSync('response.md', 'Gemini API error: ' + error.message + '\n\nPlease try again or check the GEMINI_API_KEY secret.');
            }
          }

          main();
          SCRIPT

          node on-demand.js

      - name: Post response
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let response = 'Failed to generate response. Check the Actions log for details.';

            try {
              response = fs.readFileSync('response.md', 'utf8');
            } catch (e) {
              console.log('No response file found');
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Gemini Assistant Response\n\n${response}\n\n---\n*Powered by Gemini AI | Request reviews with \`@gemini-cli /code-review\` or ask questions*`
            });
